# specify the most recent version32 of Docker Compose
version: '3.7'

#specify which services to have running within our Docker host
services:

  web:
    # Look in the current directory . for the Dockerfile
    build: .

    # start up the local server
    command: python manage.py runserver 0.0.0.0:8000

    #syncs the Docker filesystem with our local computer’s filesystem
    volumes:
      - .:/alpha

    # specify the ports to expose within Docker
    ports:
      - 8000:8000